services:
  ae_shop_nginx:
    image: nginx:1.27
    container_name: ae_shop_nginx
    hostname: ae_shop
    restart: unless-stopped
    profiles:
      - production
    depends_on:
      - ae_shop_api
      - ae_shop_frontend
      - ae_shop_maridb
      - ae_shop_strapi
    labels:
      prog: "aeshop"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - frontend_build_volume:/var/www/html
      - ${NGINX_CONFIG_FILE}:/etc/nginx/conf.d/default.conf
      - ${CONFIG_PATH}/.htpasswd:/etc/nginx/.htpasswd:ro
      - ${CONFIG_PATH}/ssl:/etc/nginx/ssl:ro
      - shop_upload_volume:/var/www/html/static/uploads
    networks:
      - ae_shop_network

  ae_shop_nginx_debug:
    image: nginx:1.27
    container_name: ae_shop_nginx
    hostname: ae_shop
    restart: unless-stopped
    profiles:
      - debug
    depends_on:
      - ae_shop_api
      - ae_shop_frontend
      - ae_shop_phpmyadmin
    labels:
      prog: "aeshop"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - frontend_build_volume:/var/www/html
      - ${NGINX_CONFIG_FILE}:/etc/nginx/conf.d/default.conf
      - ${CONFIG_PATH}/.htpasswd:/etc/nginx/.htpasswd:ro
      - ${CONFIG_PATH}/ssl:/etc/nginx/ssl:ro
      - shop_upload_volume:/var/www/html/static/uploads
    networks:
      - ae_shop_network

  ae_shop_frontend:
    image: ae_shop_frontend:latest
    container_name: ae_shop_frontend
    hostname: ae_shop_frontend
    restart: unless-stopped
    profiles:
      - production
      - debug
    labels:
      prog: "aeshop"
    build:
      context: frontend
    ports:
      - "3000:3000"
    env_file:
      - ${ENV_FILE}
    volumes:
      - ./frontend/app:/usr/src/app
      - frontend_build_volume:/usr/src/app/build
      - shop_frontend_node_modules_volume:/usr/src/app/node_modules
      - shop_upload_volume:/usr/src/app/public/static/uploads
    networks:
      - ae_shop_network

  ae_shop_api:
    build:
      context: ./api
    container_name: ae_shop_api
    hostname: ae_shop_api
    restart: unless-stopped
    profiles:
      - production
      - debug
    ports:
      - "8088:8088"
    labels:
      prog: "aeshop"
    env_file:
      - ${ENV_FILE}
    volumes:
      - ./api/app:/code/app
      - shop_upload_volume:/code/app/public/uploads
    networks:
      - ae_shop_network

  ae_shop_mariadb:
    image: mariadb:11.4.2-noble
    container_name: ae_shop_mariadb
    hostname: ae_shop_mariadb
    restart: unless-stopped
    profiles:
      - production
    labels:
      prog: "aeshop"
    env_file:
      - ${ENV_FILE}
    volumes:
      - ${CONFIG_PATH}/shop-database/mysql/data:/var/lib/mysql
      - ${CONFIG_PATH}/mysql/my.cnf:/etc/mysql/my.cnf:ro
    ports:
      - "3307:3307"
    networks:
      - ae_shop_network

  ae_shop_phpmyadmin:
    image: phpmyadmin:5.2
    container_name: ae_shop_phpmyadmin
    hostname: ae_shop_pma
    restart: unless-stopped
    profiles:
      - debug
    labels:
      prog: "aeshop"
    volumes:
      - ${CONFIG_PATH}/mysql/custom-phpmyadmin.conf:/etc/apache2/conf-enabled/custom-phpmyadmin.conf:ro
    ports:
      - 8080:80
    env_file:
      - ${ENV_FILE}
    networks:
      - ae_shop_network

  ae_shop_strapi:
    build:
      context: ./strapi
    container_name: ae_shop_strapi
    hostname: ae_shop_strapi
    restart: unless-stopped
    profiles:
      - production
    labels:
      prog: "aeshop"
    env_file:
      - ${ENV_FILE}
    ports:
      - "1337:1337"
    volumes:
      - ./strapi:/srv/app
      - ${CONFIG_PATH}/strapi-public:/srv/app/public
      - shop_upload_volume:/srv/app/public/uploads
    depends_on:
      - ae_shop_mariadb
    networks:
      - ae_shop_network

networks:
  ae_shop_network:
    external: true
    labels:
      prog: "aeshop"

volumes:
  frontend_build_volume:
    labels:
      prog: "aeshop"
  shop_frontend_node_modules_volume:
    labels:
      prog: "aeshop"
  shop_upload_volume:
      external: true