"""Init migration

Revision ID: 579f86409438
Revises: 
Create Date: 2024-09-24 14:29:03.217394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '579f86409438'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('zipcode', sa.String(length=9), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=18), nullable=True),
    sa.Column('website', sa.String(length=128), nullable=True),
    sa.Column('tax_id', sa.String(length=128), nullable=True),
    sa.Column('activated_ts', sa.DateTime(), nullable=True),
    sa.Column('activated_by', sa.String(length=36), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_companies_uuid'), 'companies', ['uuid'], unique=False)
    op.create_table('panel_backcover_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_panel_backcover_type_id'), 'panel_backcover_type', ['id'], unique=False)
    op.create_table('panel_cell_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_panel_cell_types_id'), 'panel_cell_types', ['id'], unique=False)
    op.create_table('panel_color',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_panel_color_id'), 'panel_color', ['id'], unique=False)
    op.create_table('panel_design',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_panel_design_id'), 'panel_design', ['id'], unique=False)
    op.create_table('panel_series',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_panel_series_id'), 'panel_series', ['id'], unique=False)
    op.create_table('users',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('user', 'manager', 'publisher', 'admin', name='roleenum'), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('position_title', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=18), nullable=True),
    sa.Column('utc_offset', sa.SmallInteger(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('terms_accepted', sa.Boolean(), nullable=True),
    sa.Column('policy_accepted', sa.Boolean(), nullable=True),
    sa.Column('news_subscribe', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=False)
    op.create_table('panels',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('singularity', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('files', sa.JSON(), nullable=False),
    sa.Column('images', sa.JSON(), nullable=False),
    sa.Column('min_power', sa.SmallInteger(), nullable=True),
    sa.Column('max_power', sa.SmallInteger(), nullable=True),
    sa.Column('length', sa.SmallInteger(), nullable=True),
    sa.Column('width', sa.SmallInteger(), nullable=True),
    sa.Column('height', sa.SmallInteger(), nullable=True),
    sa.Column('weight', sa.SmallInteger(), nullable=True),
    sa.Column('efficiency', sa.SmallInteger(), nullable=True),
    sa.Column('warranty', sa.SmallInteger(), nullable=True),
    sa.Column('price', sa.SmallInteger(), nullable=True),
    sa.Column('weee', sa.String(length=128), nullable=True),
    sa.Column('units_per_pallet', sa.SmallInteger(), nullable=True),
    sa.Column('units_per_container', sa.SmallInteger(), nullable=True),
    sa.Column('stock', sa.SmallInteger(), nullable=True),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.Column('cell_type_id', sa.Integer(), nullable=True),
    sa.Column('design_id', sa.Integer(), nullable=True),
    sa.Column('back_cover_type_id', sa.Integer(), nullable=True),
    sa.Column('module_color_id', sa.Integer(), nullable=True),
    sa.Column('frame_color_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['back_cover_type_id'], ['panel_backcover_type.id'], ),
    sa.ForeignKeyConstraint(['cell_type_id'], ['panel_cell_types.id'], ),
    sa.ForeignKeyConstraint(['design_id'], ['panel_design.id'], ),
    sa.ForeignKeyConstraint(['frame_color_id'], ['panel_color.id'], ),
    sa.ForeignKeyConstraint(['module_color_id'], ['panel_color.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['panel_series.id'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_panels_efficiency'), 'panels', ['efficiency'], unique=False)
    op.create_index(op.f('ix_panels_height'), 'panels', ['height'], unique=False)
    op.create_index(op.f('ix_panels_length'), 'panels', ['length'], unique=False)
    op.create_index(op.f('ix_panels_max_power'), 'panels', ['max_power'], unique=False)
    op.create_index(op.f('ix_panels_min_power'), 'panels', ['min_power'], unique=False)
    op.create_index(op.f('ix_panels_model'), 'panels', ['model'], unique=False)
    op.create_index(op.f('ix_panels_price'), 'panels', ['price'], unique=False)
    op.create_index(op.f('ix_panels_stock'), 'panels', ['stock'], unique=False)
    op.create_index(op.f('ix_panels_uuid'), 'panels', ['uuid'], unique=False)
    op.create_index(op.f('ix_panels_warranty'), 'panels', ['warranty'], unique=False)
    op.create_index(op.f('ix_panels_weight'), 'panels', ['weight'], unique=False)
    op.create_index(op.f('ix_panels_width'), 'panels', ['width'], unique=False)
    op.create_table('user_company',
    sa.Column('user_uuid', sa.String(length=36), nullable=False),
    sa.Column('company_uuid', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['company_uuid'], ['companies.uuid'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('user_uuid', 'company_uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_company')
    op.drop_index(op.f('ix_panels_width'), table_name='panels')
    op.drop_index(op.f('ix_panels_weight'), table_name='panels')
    op.drop_index(op.f('ix_panels_warranty'), table_name='panels')
    op.drop_index(op.f('ix_panels_uuid'), table_name='panels')
    op.drop_index(op.f('ix_panels_stock'), table_name='panels')
    op.drop_index(op.f('ix_panels_price'), table_name='panels')
    op.drop_index(op.f('ix_panels_model'), table_name='panels')
    op.drop_index(op.f('ix_panels_min_power'), table_name='panels')
    op.drop_index(op.f('ix_panels_max_power'), table_name='panels')
    op.drop_index(op.f('ix_panels_length'), table_name='panels')
    op.drop_index(op.f('ix_panels_height'), table_name='panels')
    op.drop_index(op.f('ix_panels_efficiency'), table_name='panels')
    op.drop_table('panels')
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_panel_series_id'), table_name='panel_series')
    op.drop_table('panel_series')
    op.drop_index(op.f('ix_panel_design_id'), table_name='panel_design')
    op.drop_table('panel_design')
    op.drop_index(op.f('ix_panel_color_id'), table_name='panel_color')
    op.drop_table('panel_color')
    op.drop_index(op.f('ix_panel_cell_types_id'), table_name='panel_cell_types')
    op.drop_table('panel_cell_types')
    op.drop_index(op.f('ix_panel_backcover_type_id'), table_name='panel_backcover_type')
    op.drop_table('panel_backcover_type')
    op.drop_index(op.f('ix_companies_uuid'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
