name: AESS CI/CD Self-Hosted Action Runner

on:
  push:
    branches: [deploy]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: deploy
      - name: up
        run: echo ${{ secrets.AESS_SUDO_PASSWORD }} | sudo -S bin/run.sh -p -d
      - name: prune
        run: yes | echo ${{ secrets.AESS_SUDO_PASSWORD }} | sudo -S docker system prune
