name: Hetzner AE Online Shop CI/CD Pipeline

on:
  push:
    branches:
      - deploy
  pull_request:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AESS.AESS_SERVER_HOST }}
          username: ${{ secrets.AESS.AESS_SERVER_USER }}
          key: ${{ secrets.AESS.AESS_SSH_KEY }}
          script: |
            cd /home/shop
            git checkout deploy
            git pull origin deploy
            chmod +x ./bin/run.sh
            ./bin/run.sh -p -d
